### PR TITLE
fix(ui): resolve android back handler issue

### LINKED ISSUE #70: [UI]: back button doesn't close modal popup
**Describe the bug**
For android users it's common to close popups by press back button on system ui. But it doesn't close connect popup.
image

**To Reproduce**
0. You need android phone
1. Go to https://ton-connect.github.io/demo-dapp-with-react-ui/
2. Click on "Connect Wallet"
3. Click on Back button
4. Popup will not close

**Expected behavior**
Popup should close like in Tonkeeper when we see transaction info
image

### PR DESCRIPTION
**Pull request by thekiba**
Closes #70

### CODE REVIEW

File: packages/ui/src/ton-connect-ui.ts [hunk 1]
```diff
@@ -164,6 +164,10 @@ export class TonConnectUI {
                 merged.buttonRootId = options.buttonRootId;
             }
 
+            if (options.enableAndroidBackHandler !== undefined) {
+                merged.enableAndroidBackHandler = options.enableAndroidBackHandler;
+            }
+
             return merged;
```
Comment (galaxycores) [inline packages/ui/src/ton-connect-ui.ts:171]: return merged;
